---
- name: Update web servers
  hosts: Web02
  become: yes

  tasks:
    - name: Install Apache2
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Ensure Apache2 service is running and enabled
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes

    - name: Copy index file to web server
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/index.html

- name: Configure database server
  hosts: db01
  become: yes

  tasks:
    - name: Install MariaDB server
      ansible.builtin.apt:
        name: mariadb-server
        state: present

    - name: Install python Mysql Dependency 
      ansible.builtin.apt:
        name: python3-pymysql
        state: present

    - name: Ensure MariaDB service is running and enabled
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create a new database
      community.mysql.mysql_db:
        name: accounts
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create database user with name 'vprofile'
      community.mysql.mysql_user:
        name: vprofile
        password: 'admin123'
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

